name: The program does not behave correctly.

description: File a bug report

body:

  - type: markdown
    attributes:
      value: |
        ## Hey! Make sure this is not from any other repo. If it is, please report this issue to the correct repo.

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Enter your Windows version. For Windows 10 and 11, include the build number.
      placeholder: ex. Windows 10 22H2
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
      placeholder: Attach screenshots for clarity.
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: If you have hints on why this bug happens, you can express it here.
